addSbtPlugin("io.spray"       % "sbt-revolver"        % "0.10.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"         % "0.10.4")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.11.0")
addSbtPlugin("dev.zio"        % "zio-sbt-ecosystem"   % "0.4.0-alpha.8")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")